{
 "title": "Nonogram Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Nonogram Completion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nonogram completed",
   "type": "stat",
   "description": "In the given time range",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS completed_count\nFROM nonogram_logs\nWHERE ended IS NOT NULL\nAND $__timeFilter(ended)"
    }
   ]
  },
  {
   "title": "Fastest Nonogram",
   "type": "gauge",
   "description": "in the given time range",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  started,\n  ended,\n  EXTRACT(EPOCH FROM (ended - started)) AS duration_seconds\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND started IS NOT NULL\n  AND $__timeFilter(ended)\nORDER BY duration_seconds ASC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Average completion time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(EXTRACT(EPOCH FROM (ended - started))) AS avg_duration_seconds\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND started IS NOT NULL\n  AND $__timeFilter(ended);\n"
    }
   ]
  },
  {
   "title": "Longest completion time",
   "type": "gauge",
   "description": "in the given time range",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  started,\n  ended,\n  EXTRACT(EPOCH FROM (ended - started)) AS duration_seconds\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND started IS NOT NULL\n  AND $__timeFilter(ended)\nORDER BY duration_seconds DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Nonogram completed Overall",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS completed_count\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n"
    }
   ]
  },
  {
   "title": "Nonogram Completed per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', ended) AS time,\n  COUNT(*) AS completed_count\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND $__timeFilter(ended)\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Nonogram Completed per Hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', ended) AS time,\n  COUNT(*) AS completed_count\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND $__timeFilter(ended)\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Nonogram Completed per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', ended) AS time,\n  COUNT(*) AS completed_count\nFROM nonogram_logs\nWHERE ended IS NOT NULL\n  AND $__timeFilter(ended)\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Best Streak in 3 minutes",
   "type": "gauge",
   "description": "The maximum nonogram completions count in 3 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH durations AS (\n  SELECT ended\n  FROM nonogram_logs\n  WHERE ended IS NOT NULL\n    AND $__timeFilter(ended)\n)\nSELECT MAX(cnt) AS best_streak\nFROM (\n  SELECT COUNT(*) OVER (\n    ORDER BY ended\n    RANGE BETWEEN '3 minutes'::interval PRECEDING AND CURRENT ROW\n  ) AS cnt\n  FROM durations\n) t;\n"
    }
   ]
  },
  {
   "title": "Best Streak in 5 minutes",
   "type": "gauge",
   "description": "The maximum nonogram completions count in 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH durations AS (\n  SELECT ended\n  FROM nonogram_logs\n  WHERE ended IS NOT NULL\n    AND $__timeFilter(ended)\n)\nSELECT MAX(cnt) AS best_streak\nFROM (\n  SELECT COUNT(*) OVER (\n    ORDER BY ended\n    RANGE BETWEEN '5 minutes'::interval PRECEDING AND CURRENT ROW\n  ) AS cnt\n  FROM durations\n) t;\n"
    }
   ]
  },
  {
   "title": "Best Streak in 1 hour",
   "type": "gauge",
   "description": "The maximum nonogram completions count in 1 hour",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH durations AS (\n  SELECT ended\n  FROM nonogram_logs\n  WHERE ended IS NOT NULL\n    AND $__timeFilter(ended)\n)\nSELECT MAX(cnt) AS best_streak\nFROM (\n  SELECT COUNT(*) OVER (\n    ORDER BY ended\n    RANGE BETWEEN '60 minutes'::interval PRECEDING AND CURRENT ROW\n  ) AS cnt\n  FROM durations\n) t;\n"
    }
   ]
  }
 ]
}